language: python
python:
  - 2.7
env:
  - FLASK=0.10.1
  - DB=mysql
services: mysql
before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS phoenix;" -uroot; fi
install:
  - pip install -q Flask==$FLASK --use-mirrors
  - ./configure
script:
  - nosetests --verbosity=3 -x .
addons:
    code_climate:
        repo_token: d291ccff6d822a69ac1e2b594bdf7dede9144c2ff9b9fb03bc953255f5ac4b74
